BOT_TOKEN = "YOUR_BOT_TOKEN"

API_ID = 123456
API_HASH = "YOUR_API_HASH"

OWNER_ID = 123456789

OWNER_USERNAME = "DA_R_KS_I_DE"
UPDATE_CHANNEL = "https://t.me/AniWorld_Bot_Hub"

DOWNLOAD_DIR = "downloads/"
OUTPUT_DIR = "output/"

MAX_SPLIT_SIZE = 2000000000

PROGRESS_REFRESH = 4
